SELECT
    j.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM ITEM_INFO i
INNER JOIN (
    SELECT a.ITEM_ID AS ITEM_ID
    FROM ITEM_TREE a
    LEFT JOIN ITEM_TREE b
        ON a.ITEM_ID = b.PARENT_ITEM_ID
    WHERE b.PARENT_ITEM_ID IS NULL
) j
    ON i.ITEM_ID = j.ITEM_ID
ORDER BY j.ITEM_ID DESC
