SELECT 
    e.ID,
    COALESCE(c.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA e
LEFT JOIN(
    SELECT
        PARENT_ID,
        COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) c ON e.ID = c.PARENT_ID

