-- 코드를 작성해주세요
SELECT 
S.ID AS ID, 
    S.GENOTYPE AS GENOTYPE, 
    P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS S
    INNER JOIN ECOLI_DATA AS P
        ON S.PARENT_ID = P.ID
WHERE 
    (S.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
    
ORDER BY S.ID ASC;