SELECT 
    u.USER_ID,
    u.NICKNAME,
    b.TOTAL_SALES
FROM USED_GOODS_USER u
INNER JOIN(
    SELECT
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
) b
    ON u.USER_ID = b.WRITER_ID
ORDER BY b.TOTAL_SALES ASC