-- 코드를 작성해주세요


SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    Dev.SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM (
        SELECT 
            YEAR(DIFFERENTIATION_DATE) AS YEAR, 
            MAX(SIZE_OF_COLONY) AS SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS Dev
JOIN ECOLI_DATA AS E
    ON Dev.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV ASC