SELECT
    f.ID,
    n.FISH_NAME,
    f.LENGTH
FROM FISH_INFO f
INNER JOIN (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
) max_f
    ON f.FISH_TYPE = max_f.FISH_TYPE AND f.LENGTH = max_f.MAX_LENGTH
INNER JOIN FISH_NAME_INFO n
    ON n.FISH_TYPE = f.FISH_TYPE
ORDER BY f.ID ASC